// Generated by CoffeeScript 1.6.3
(function() {
  var NavigationViewModel, Opportunity, OpportunityViewModel, namespace,
    __slice = [].slice,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  namespace = function(target, name, block) {
    var item, top, _i, _len, _ref, _ref1;
    if (arguments.length < 3) {
      _ref = [(typeof exports !== 'undefined' ? exports : window)].concat(__slice.call(arguments)), target = _ref[0], name = _ref[1], block = _ref[2];
    }
    top = target;
    _ref1 = name.split('.');
    for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
      item = _ref1[_i];
      if (item.length > 0) {
        target = target[item] || (target[item] = {});
      } else {
        target = window;
      }
    }
    return block(target, top);
  };

  NavigationViewModel = (function() {
    function NavigationViewModel() {
      this.filterFields = __bind(this.filterFields, this);
      this.defineField = __bind(this.defineField, this);
      this.createFieldMap = __bind(this.createFieldMap, this);
      var _this = this;
      this.opportunity = new Models.Opportunity();
      this.fieldMap = ko.observableArray();
      this.fieldSearchText = ko.observable();
      this.createFieldMap();
      this.fieldSearchText.subscribe(function(newVal) {
        return _this.filterFields(newVal);
      });
    }

    NavigationViewModel.prototype.createFieldMap = function() {
      var _this = this;
      return $('div[data-group]').each(function(index, groupElement) {
        var dataGroup, id;
        id = $(groupElement).attr('id');
        if (id == null) {
          throw new Error('Id for the group element is required in order to collapse/ expand it..');
        }
        dataGroup = _this.defineField($(groupElement).data('group'), id);
        $('div[data-field]', groupElement).each(function(index, fieldElement) {
          var field;
          id = $(fieldElement).attr('id');
          if (id == null) {
            throw new Error('Id for the field element is required for navigation.');
          }
          field = _this.defineField($(fieldElement).data('field'), id);
          return dataGroup.Fields.push(field);
        });
        return _this.fieldMap.push(dataGroup);
      });
    };

    NavigationViewModel.prototype.defineField = function(definition, elementId) {
      if (typeof definition !== 'object') {
        throw new Error('Error while creating the field map. Attribute names must have double qotes around it.');
      }
      return {
        Name: definition.name,
        ID: elementId,
        Attibute: definition.attribute,
        Fields: ko.observableArray(),
        Display: ko.observable(true)
      };
    };

    NavigationViewModel.prototype.filterFields = function(searchTerm) {
      if (searchTerm == null) {
        return;
      }
      searchTerm = searchTerm.toLowerCase();
      return this.fieldMap().forEach(function(section) {
        return section.Fields().forEach(function(field) {
          if (field.Name.toLowerCase().indexOf(searchTerm) === -1) {
            return field.Display(false);
          } else {
            return field.Display(true);
          }
        });
      });
    };

    return NavigationViewModel;

  })();

  namespace('Models', function(exports) {
    return exports.NavigationViewModel = NavigationViewModel;
  });

  Opportunity = (function() {
    function Opportunity() {
      this.isSupplied = __bind(this.isSupplied, this);
      this.isRequired = __bind(this.isRequired, this);
      this.OpportunityName = ko.observable();
      this.TransactionType = ko.observable();
      this.Commission = ko.observable();
      this.StartDate = ko.observable();
      this.AwardDate = ko.observable();
    }

    Opportunity.prototype.isRequired = function(fieldId) {
      var _this = this;
      return ko.computed(function() {
        return Boolean(fieldId.length % 2);
      });
    };

    Opportunity.prototype.isSupplied = function(fieldId) {
      var _this = this;
      return ko.computed(function() {
        return Boolean(fieldId.length % 2);
      });
    };

    return Opportunity;

  })();

  namespace('Models', function(exports) {
    return exports.Opportunity = Opportunity;
  });

  OpportunityViewModel = (function() {
    function OpportunityViewModel() {
      this.data = new Models.Opportunity();
    }

    return OpportunityViewModel;

  })();

  namespace('Models', function(exports) {
    return exports.OpportunityViewModel = OpportunityViewModel;
  });

}).call(this);

/*
//@ sourceMappingURL=viewmodels.map
*/
